### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by kahaaga**
A suggestion for CausalityTools 2.0. The docs are [here](https://juliadynamics.github.io/CausalityTools.jl/previews/PR187/).

- This is a complete re-write, so the git diff is essentially useless.  The online documentation is the best place to get an overview.
- Deprecations have been added where relevant. 
- I have on purpose made th

## Content

The information measure API has been completely overhauled. All functionality from TransferEntropy.jl has been moved here. Information measures now come in many flavors (not only Shannon-type). All quantities both have dedicated estimators, but can be estimated any compatible lower-level estimator like `DifferentialEntropyEstimator` or `ProbabilitiesEstimator`. Users thus have access to a large number of estimation methods, with and without bias correction.

- [x] Conditional entropy
- [x] Mutual information
- [x] Conditional mutual information
- [x] Transfer entropy

Cross mapping measures. A complete rewrite was done in 1.6. I just list the API here for overview's sake.

- [x] A common `crossmap(::CrossmapMeasure, est::CrossMapEstimator, x, y)` method
- [x] `ConvergentCrossMapping <: CrossmapMeasure`
- [x] `PairwiseAsymmetricEmbedding <: CrossmapMeasure`
- [x] A few different crossmap estimators.

### CODE REVIEW

**Comment by Datseris** [comment]
@kahaaga can we please add the convenience dispatch:
```julia
transferentropy(emb::EmbeddingTE, args...) = transferentropy(TEShannon(; embedding = emb), args...)
```
so that one doesn't have to go into details discussing different definitions of entropy?

**Comment by kahaaga** [comment]
> @kahaaga can we please add the convenience dispatch:
> 
> ```julia
> transferentropy(emb::EmbeddingTE, args...) = transferentropy(TEShannon(; embedding = emb), args...)
> ```
> 
> so that one doesn't have to go into details discussing different definitions of entropy?

Done. Check out `v2` again, and things like `transferentropy(EmbeddingTE(), ValueHistogram(3), x, y)` will work.

**Comment by Datseris** [comment]
I'll slowly start reviewing this now. But I start anyways with the same comment as the one I had for ComplexityMeasures.jl. `crossmap(::CrossmapMeasure, est::CrossMapEstimator, x, y)` feels unecessarily complicated and not of much relevance in practice, as it can be replaced by `crossmap(est::CrossMapEstimator, x, y)` where the estimator encapsulates a definition. Same for TE and everything else. The other thing I noticed during the workshop is that I think it is important in the TE docs for one to first start by documenting a method `te(embedding, prob_est, x, y)`. Then a different section exposes the more complicated methods.

**Comment by Datseris** [comment]
Ah, I see that the suggestion I had is pretty much already in place; I was reading the top-level issue comment that had a description also with definition.

**Comment by kahaaga** [comment]
> Ah, I see that the suggestion I had is pretty much already in place; I was reading the top-level issue comment that had a description also with definition.

Which suggestion and which top-level comment, specifically? I'm not following :D

**Comment by Datseris** [comment]
I suggested to hcange the interfface of `function(definition, estimator, x, y)` into `function(estimator, x, y)`. But it appears that this is already done when possible.

**Comment by kahaaga** [comment]
@Datseris I just realized that I haven't actually estimated a contingency-matrix based *estimator*, only a type that *represents* a contingency matrix. For a consistent API, there should be a generic *estimator* that computes the relevant contingency matrix for the user if compatible input data are given (categorical or integer data of some kind). Behind the scenes, this estimator computes a `ContingencyMatrix` and feeds it to relevant functions.

```julia

Base.@kwdef struct Contingency{P <: Union{Nothing, ProbabilitiesEstimator}} <: ProbabilitiesEstimator
    est::P = nothing
end

# For purely categorical data
mutualinfo(Contingency(), x, y)
condmutualinfo(Contingency(), x, y, z)

# If data need to be discretized first, then provide a `ProbabilitiesEstimator` to `Contingency`
mutualinfo(Contingency(ValueHistogram(3)), x, y)
condmutualinfo(Contingency(ValueHistogram(3)), x, y, z)
```

Any thoughts?

**Comment by Datseris** [comment]
I don't understand what this is doing. Isn't `mutualinfo(Contingency(ValueHistogram(3)), x, y)` the same as the current `mutualinfo(ValueHistogram(3), x, y)` ...?

**Comment by kahaaga** [comment]
> I don't understand what this is doing. Isn't `mutualinfo(Contingency(ValueHistogram(3)), x, y)` the same as the current `mutualinfo(ValueHistogram(3), x, y)` ...?

In short, `f(measure, c::ContingencyMatrix)` always uses the sum-definition of whatever `measure` it computes. On the other hand, `f(measure, est::ProbabilitiesEstimator, args...)` always uses the naive sum-of-entropies definition when it exists for `measure`. For some measures these operations are equivalent (like Shannon MI/CMI), but for others they are not (like Sarbu's Renyi MI, because Sarbu's definition deosn't admit a simple sum-of-entropies definition). 

What happens is therefore:

- `mutualinfo(MIShannon(), c::ContingencyMatrix` computes MI from the contingency matrix using the sum-definition of Shannon MI.
- `mutualinfo(MIShannon(), ValueHistogram(3), x, y)` computes MI from the three-entropies definition of Shannon MI, which is equivalent equivalent to the sum-definition. This is faster than using the contingency matrix because it only has to compute the relevant marginals, not the entire contingency matrix. But it doesn't work for categorical variables, because it uses `Dataset`s.
- `mutualinfo(MIRenyiSarbu(), c::ContingencyMatrix)` computes Sarbu's definition of Renyi MI from the contingency matrix using the sum-definition. 
- `mutualinfl(MIRenyiSarbu(), ::ValueHistogram,x, y)` isn't defined.

Thus, the `ContingencyMatrix` is sort of a "fallback" estimation method when faster alternatives aren't possible. The reason why I want `Contingency` as its own estimator is so that it can be plugged in, just like `ValueHistogram` or other probabilities estimator, to higher-level methods (e.g. the PC-algorithm or some conditional independence test). After all, it is just another (high-dimensional) probabilities estimator, so it should behave the same way as all other probabilities estimators.

**Comment by Datseris** [comment]
buhuhu i'm sorry i am completely overwhelmed with moving to the UK and preparing other upcoming workshops and DynamicalSystems.jl 3.0 :( :( :(  I will try to have more look here, but for the moment, how necessary is it to tag a stable release? Is it feasible for you to merge this and have this out as the current `main` with the dev docs uploaded, and not tag 2.0?

**Comment by kahaaga** [comment]
> buhuhu i'm sorry i am completely overwhelmed with moving to the UK and preparing other upcoming workshops and DynamicalSystems.jl 3.0 :( :( :( I will try to have more look here, but for the moment, how necessary is it to tag a stable release? Is it feasible for you to merge this and have this out as the current main with the dev docs uploaded, and not tag 2.0?

I completely understand your situation, @datseris! We'll have to work something out here that doesn't end up with either of us ending up completely exhausted.

I've had a talk with my group, and we all agree that getting stable release is a top priority for us now. Given the limited time left of my contract (until late fall), and everything else I have going on, I *have* to prioritize getting the already implemented methods and out there, in a stable release, as soon as possible (yesterday 😬). Not committing to a stable release now and using `main` branch is an issue, because:
1. Any material (scientific papers, workshops, book material) produced based on `main` must be updated in the future.
2. None of this material is guaranteed to have a stable release backing it.
3. Incompatible package requirements and outdated APIs will be an issue when breaking changes happen on `main`.
4. The many, many implementations of various measures that I've stripped away for this release risk not ending up in the package, because I can't finalize them until a final API is reached.
5. The same applies to new methods and workshop material I'm working on.
6. Analyses for papers I'm about to submit are based on the current API (i.e. this branch). 

As much as I want to be as thorough as we were for ComplexityMeasures.jl, I simply haven't got the time available to repeat that process. The coming six months is riddled with deadlines, and I don't have time to re-do a bunch of material. Therefore, we have to be practical. We suggest the following:

- We release v2.0 based on the API in this PR. That is: `f([measure], estimator, input_data...)`
- We accept that v2 is potentially short-lived, and that it may be superseded by V3 in the not-so-distant future.
- Our group does a code-review workshop of this PR and sort out any obvious errors/flaws.

Things do *work* at the moment, and the main thing holding this back is the API design, which inevitably a subjective matter, which we undoubtedly will discuss back and forth for some time. We don't think it is worth the trade-off to postpone everything else (submissions etc) based on design-related matters. A functional library with a stable release is more important at the moment.

In any case, the current state of V2 is far better than V1 ever was, so an immediate release is an immediate improvement already.

Does this sound reasonable, @Datseris?

**Comment by Datseris** [comment]
This does sound reasonable. I'd suggest merging this in already and continuing a review from `main` and the `dev`docs. It will make everything simpler because separate independent issues can be discussed one by one, instead of adding parallel discussions to a single PR.

**Comment by kahaaga** [comment]
> This does sound reasonable. I'd suggest merging this in already and continuing a review from main and the devdocs. It will make everything simpler because separate independent issues can be discussed one by one, instead of adding parallel discussions to a single PR.

Ok, perfect! Then I'll merge and we'll treat any problems on an issue-by-issue basis.

**Comment by kahaaga** [comment]
> EDIT: I meant, if you plan to get in more people to help reviewing, because you wrote _"Our group does a code-review workshop of this PR and sort out any obvious errors/flaws."_, it's simpler to do it from the dev docs rather than a massive v2 PR.

Sure! I'll merge this, then any changes we need to make, we do it in separate PRs.

**Pull request merged**
