### PR TITLE
Start move to v1

### PR DESCRIPTION
**Pull request by kahaaga**
I'm starting a blank branch here for v1.0 to keep track of the new documentation as it evolves, and to add things after I've re-done it in the `genembed` spirit. 

No need for review here until further notice.

### CODE REVIEW

**Comment by Datseris** [comment]
Hi there,

Sure, I can have a look at this over the weekend. I'd recommend waiting for a second pair of eyes to have a look and provide feedback before merging!

The docs are here: https://juliadynamics.github.io/CausalityTools.jl/previews/PR129/

**Comment by kahaaga** [comment]
> Sure, I can have a look at this over the weekend. I'd recommend waiting for a second pair of eyes to have a look and provide feedback before merging!

Excellent, I'll wait for your feedback before I merge.

**Comment by Datseris** [comment]
@kahaaga do you know this by the way: https://causeme.uv.es/  ?

**Comment by Datseris** [comment]
Alright, here comes my review after seeing the docs. An important point is that I think the docs should state clearly that this is about *detecting dynamical relations * and *causal inference*. I don't know what the reviewer told you, but e.g. in this paper: 

> Runge, J., Bathiany, S., Bollt, E., Camps-Valls, G., Coumou, D., Deyle, E., Glymour, C., Kretschmer, M., Mahecha, M. D., Muñoz-Marí, J., van Nes, E. H., Peters, J., Quax, R., Reichstein, M., Scheffer, M., Schölkopf, B., Spirtes, P., Sugihara, G., Sun, J., … Zscheischler, J. (2019). Inferring causation from time series in Earth system sciences. Nature Communications, 10(1), 1–13. https://doi.org/10.1038/s41467-019-10105-3

the methods that CausalityTools.jl has are referred to as *casual inference*. 


1. I'm a bit skeptical of repeating the docs of TimeseriesSurrogates.jl here instead of linking them. It will only make it harder to maintain and perhaps following a simple link isn't really that hard. The docs have the same theme and style so I think it is okay here and will save development effort along the way.
2. The docs need a paragraph in the style of "getting started" that showcases the typical workflow or something along these lines. At the moment they list the available features but you'd need to connect the docs to know how to use them.
3. There is an overall lack of runnable examples, in the sense that for most of the functionality, we have here a listing of documentation strings. If you look at the DynamicalSystems docs, I've tried that every page has at least some example that is created via runnable code. I strongly recommend to have figures that are output with Documenter, just like we do in TimeseriesSurrogates or DynamicalSystems. I saw in some docstrings you have examples inside the docstring, e.g.: 
image . I believe that removing this code and putting it just after the docstring, in a documenter block, is just much more powerful, because you see the output. This makes a massive difference in the learning experience, because you don't have to copy paste everything around. 
5. Specifically for the example figure I pasted above, I don't think it makes sense to run the same code with another keyword argument. The keyword argument `f` is already explained, you don't actually learn anything with the last two lines of code in the example.
4. I'm not sure why a package CrossMappings.jl exists, but I don't think it warrants existence as an individual package and its code should be in CausalityTools instead. Also this: https://github.com/JuliaDynamics/CrossMappings.jl/blob/master/src/convergent_cross_mapping/crossmapping.jl#L190 doesn't use the `tree_type`. I'm not sure whether there is an argument in allowing different tree types. I'd remove them from the docstrings and the source. BTW, if you are interested, this is the function I wrote for calculating CCM for my book, if we want to compare codes:
```julia
function ccm(x, y, d, τ)
    Mx = embed(x, d, τ); theiler = Theiler(0); tree = KDTree(Mx)
    idxs = bulkisearch(tree, Mx, NeighborNumber(d+1), theiler)
    ỹ = copy(y)
    for i in 1:length(Mx)
        J = idxs[i]
        xᵢ = Mx[i]; n1 = norm(xᵢ - Mx[J[1]])
        w = [exp(-norm(xᵢ - Mx[j])/n1) for j in J]
        w ./= sum(w)
        ỹ[i] = sum(w[k]*y[j] for (k, j) in enumerate(J))
    end
    return cor(y, ỹ)
end
```


Once we have examples with output, I'll have a second look here! Meanwhile, can you address https://github.com/JuliaDynamics/TimeseriesSurrogates.jl/pull/62 and https://github.com/JuliaDynamics/Entropies.jl/pull/57 ?

**Comment by Datseris** [comment]
@kahaaga judging by the lack of response here and in every other channel and repository, as well as the open issues I see in this repository, I'm assuming you are no longer active in these projects. I'll let this here for a week or so in hopes of getting a reply, but then I'll start looking for maintainers. Some of the open issues are people not being able to install the package and their fix takes 5 minutes of time. So I'm pretty sure it won't be hard to find someone that can do those things, or I'll just do them myself.

**Comment by kahaaga** [comment]
@Datseris I'll respond properly once everything on my calendar is cleared on Friday. Summary: I still intend to maintain the repo.

**Comment by kahaaga** [comment]
@Datseris Hi! This is ready to go from my side. I made the following additions/changes:

- Moved CCM stuff to a submodule within CausalityTools, rather than being in its own package, as you suggested.
- Simplified and updated the CCM code. For the most basic implementation, I've added the code that you pasted above (and added you to the list of authors). The bootstrap-based implementation I had before is still available, though.
- Added at least one runnable example to each method.
- Removed the documentation for TimeseriesSurrogates.jl (link to it instead).
- Added a "getting started" section to the first page, and added a link to suggested reading.

If this is good with you, I'll merge and release 1.0 as soon as possible.

I'll have a look at the other issues you mentioned above in the thread in the coming days.

**Review by Datseris — APPROVED** [review]
Hi @kahaaga , glad to see you back. The docs look very, very good!

I've noticed that in the main repo there are many "old" files existing from much older versions of Julia and GitHub approaches. E.g., travis, appveyor, `install_dependencies.jl`, a `deps` folder, etc. At the moment, only a Project.toml, and a `.github/workflows` is needed. Feel free to copy paste everything from the DynamicalSystems.jl over here, especially the CompatHelper script, really useful.

**Pull request merged**
