### PR TITLE
WIP: V2

### PR DESCRIPTION
**Pull request by kahaaga**
This is *extremely* WIP. It is not in any shape or form ready for review yet. I'm just opening a PR so that I can verify CI tests and that the docs build.

The docs are [here](https://juliadynamics.github.io/CausalityTools.jl/previews/PR186/).

### CODE REVIEW

**Comment by kahaaga** [comment]
@Datseris A follow up on your comment in https://github.com/JuliaDynamics/NonlinearDynamicsComplexSystemsCourses/pull/1#issuecomment-1382410948

I think the docs are in ready-ish shape to be reviewed when it comes to structure/api. I'm not done with cleaning up the internals yet, but that shouldn't matter for the user-exposed API.

**Comment by Datseris** [comment]
@kahaaga I read your comment here: https://github.com/JuliaDynamics/NonlinearDynamicsComplexSystemsCourses/pull/1#issuecomment-1382442320  

Besides the contigency matrix, is it a problem and or blocker for other things in causality tools that probability estimators do not keep 0 probablity elements? If so, we would need a second function like `fullprobabilities` that would always return probabilities for all outcome space, with 0 for "unvisited bins".

(notice that all `probabilties` are always ordered. Its just that at the moment 0 events are dropped)

**Comment by kahaaga** [comment]
> Besides the contigency matrix, is it a problem and or blocker for other things in causality tools that probability estimators do not keep 0 probablity elements? 

No, it is not a blocker, because for any multi-argument discrete information function, the input variables are separately discretized/encoded and discretized marginals are inferred from the joint discretized space. Zero-probability joint outcomes are also dropped here, but that happens completely independently of what goes on in `ComplexityMeasures`.

**Comment by Datseris** [comment]
This errors but the docs say it should work:
```julia
x = rand(100)
y = rand(100)
mutualinfo(SymbolicPermutation(m=3), x, y)
```
ArgumentError: Order of ordinal patterns and dimension of `Dataset` must match!

**Comment by kahaaga** [comment]
> This errors but the docs say it should work:

The default-to-Shannon-MI convenience function is missing. It works if you do `mutualinfo(MIShannon(), est, x, y)`.

**Comment by Datseris** [comment]
it does work, actually, my code wasn't full pulled here

**Comment by kahaaga** [comment]
> it does work, actually, my code wasn't full pulled here

Good! I still haven't gone through everything, so there are probably several more examples that are not up to date. Just post them here any if you find nonfunctional examples

**Comment by Datseris** [comment]
```
mutualinfo(MIShannon(), KraskovStögbauerGrassberger2(k=5), x, y)
```
is possible but 
```
mutualinfo(KraskovStögbauerGrassberger2(k=5), x, y)
```
isn't, but it should be I guess there is no reason to go int otoo much details about the different "definitions" of MI.

**Comment by kahaaga** [comment]
> isn't, but it should be I guess there is no reason to go int otoo much details about the different "definitions" of MI.

The KSG1/KSG2 estimators are specifically designed for Shannon MI, so the same convenience method should exist, I think.

**Comment by kahaaga** [comment]
@Datseris I'm implementing (but haven't pushed yet to this PR) convenience stuff for optimising embeddings for the workshop. I'm wondering what should be the default behaviour. The alternatives are

```julia
# User specified. No optimization by default, which results in simplest possible joint embedding 
# vectors `{ (t(i+1), t(i), s(i)) }`
basic::EmbeddingTE = EmbeddingTE() 

# Optimise using semi-automated "traditional" delay embedding (as in DynamicalSystems)
optimised::EmbeddingTE = optimize_marginals(OptimiseTraditional(), s, t, [c])

# To be implemented in various forms
hyperoptimised::EmbeddingTE = optimize_marginals(FancyMethod(), s, t, c)

# Two alternatives for defining the default transfer entropy measure
transferentropy(est, s, t, [c]) = transferentropy(TEShannon(embedding = basic), est, s, t, [c])
transferentropy(est, s, t, [c]) = transferentropy(TEShannon(embedding = optimal), est, s, t, [c])
```

Which one do you think makes the most sense? 

The various packages out there for transfer entropy do different things, all the way from just providing manual embedding options, to doing very sophisticated optimized embedding searches. I think maybe I like the intermediate "traditional" embedding search as the default, because for anything beyond AR1-systems, there is some memory involved that is not caputed by the default user-speficied version.

**Comment by Datseris** [comment]
this seems okay to me, but what is the embeddings "optimizing" ? what is the "cost" that you minimize? I am not sure I understand this. I guess you have here TE from Y to X conditional on Z, right?

**Comment by kahaaga** [comment]
> this seems okay to me, but what is the embeddings "optimizing" ? what is the "cost" that you minimize? I am not sure I understand this. I guess you have here TE from Y to X conditional on Z, right?

Transfer entropy `TE(s -> t])` or `TE(s -> t | c)` is the conditional mutual information `I(T_future; S_past | T_past, [C_past])`. Assuming that each input `s`, `t` and `c` is a timeseries, the `S_past` and `T_past` (and `C_past`, if included) marginals are *embeddings*. 

This particular optimisation isn't about minimizing some cost function. It is just a question of finding an appropriate embedding for each of the embedding terms that go into `I(T_future; S_past | T_past)`. 

Other methods (that are not part of this PR), like the bootstrap-based nonuniform embedding (BBNUE), find embedding parameters by minimizing conditional mutual information `I(T_future, C_i | B)` between the candidate variable `C_i` and previously selected variables `B`.

**Comment by Datseris** [comment]
aaaaa ok thats perfect

**Comment by kahaaga** [comment]
> aaaaa ok thats perfect

Ok, then I'll make this DynamicalSystems.jl-based traditional embedding approach the default, as I described in my comment above.

**Pull request closed without merging**
